fos_http_cache:
    cache_control:
        defaults:
            overwrite: true
        rules:
            - match:
                  path: ^/
              headers:
                  overwrite: false
                  cache_control: { public: true, max_age: 15, s_maxage: 30 }
                  etag: 'strong'
